test:
  image: python:3.7
  script:
    - cd src && python setup.py install
    - create_dataset -n 0.01 -p mini -d
    - run_qallse -i mini/event000001000-hits.csv
    - create_dataset -n 0.1 -d -o /tmp
    - cd examples && python build_qubo.py && python sample_qubo_qbsolv.py && python sample_qubo_neal.py
#  only:
#    - master
